### ISSUE TITLE
Issue Importing bornagain modules for python3 on Mac

### ISSUE THREAD

**Issue by gdoerk** [scgmlz/BornAgain#905]
### Expected Behavior

Bornagain 1.16.0 cannot be used with python3, due to an issue with importing.  The GUI seems to works fine,  but I cannot install the libraries in a way that required modules are accessible.  Even if I generate Python code from the GUI, that Python code cannot run. 

I also tried to install in a different directory, and add that to the path, but it didn't help.  

### Actual behavior

As an example, executing this command:

> python3 /Applications/BornAgain.app/Contents/share/BornAgain-1.16/Examples/python/simulation/ex01_BasicParticles/CylindersAndPrisms.py

Produces this error message:

>Traceback (most recent call last):
  File "/Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/libBornAgainFit.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bornagain._libBornAgainFit'
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
  File "/Applications/BornAgain.app/Contents/share/BornAgain-1.16/Examples/python/simulation/ex01_BasicParticles/CylindersAndPrisms.py", line 4, in <module>
    import bornagain as ba
  File "/Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/__init__.py", line 10, in <module>
    from .libBornAgainFit import *
  File "/Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/libBornAgainFit.py", line 17, in <module>
    _libBornAgainFit = swig_import_helper()
  File "/Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/libBornAgainFit.py", line 16, in swig_import_helper
    return importlib.import_module('_libBornAgainFit')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/lib/BornAgain-1.16/_libBornAgainFit.so, 2): Library not loaded: @rpath/Python.framework/Versions/3.7/Python
  Referenced from: /Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/lib/BornAgain-1.16/_libBornAgainFit.so
  Reason: image not found

Similar error message is produced with the following command (or from any code that includes a line "import bornagain":

>python3 -c "import bornagain"

### Steps to reproduce the behavior

Installed BornAgain as described in web documentation.
Configured Python for BornAgain by executing command:

>python3 /Applications/BornAgain.app/Contents/libexec/BornAgain-1.16/bornagain_python_install.py

Attempted to compile Python script with "import bornagain" command.

### Platforms affected

MacOS Mojave (v. 10.14)
Python 3.7.7

**Comment by juanmcloaiza** [comment]
Let me write some comments on your error message:

    Traceback (most recent call last):
    File "/Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/libBornAgainFit.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/init.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    File "", line 1014, in _gcd_import
    File "", line 991, in _find_and_load
    File "", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'bornagain._libBornAgainFit'

It seems that the python version is 3.8, whereas in your issue, it is reported to be 3.7. You can check this by typing `which python` or `which python3` on the terminal.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/Applications/BornAgain.app/Contents/share/BornAgain-1.16/Examples/python/simulation/ex01_BasicParticles/CylindersAndPrisms.py", line 4, in
    import bornagain as ba
    File "/Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/init.py", line 10, in
    from .libBornAgainFit import *
    File "/Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/libBornAgainFit.py", line 17, in
    _libBornAgainFit = swig_import_helper()
    File "/Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/libBornAgainFit.py", line 16, in swig_import_helper
    return importlib.import_module('_libBornAgainFit')
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/init.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    ImportError: dlopen(/Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/lib/BornAgain-1.16/_libBornAgainFit.so, 2): Library not loaded: @rpath/Python.framework/Versions/3.7/Python
    Referenced from: /Users/gregorydoerk/Desktop/Python/lib/python/site-packages/bornagain-1.16-py3.8.egg/bornagain/lib/BornAgain-1.16/_libBornAgainFit.so
    Reason: image not found

Yet, in the third line from the bottom of this error message, there is actually a reference to python 3.7. My guess is that 1. the python path has not been correctly set  and/or 2. the python interpreter invoked does not match the bornagain installation version. 

Let's try the following:

 1. Locate the file "_libBornAgainFit.so" -- you can do this in a terminal using the command `find`, e.g. `find / -iname "_libBornAgainFit.so"`

 2. Set the `PYTHONPATH` environment variable to the path of the directory containing the file just found. In a terminal type: `export PYTHONPATH=/the/path/found/in/step1`. Be careful not to include the `_libBornAgainFit.so` itself in the path!

3. In a terminal, type `whereis python`. You will get a list of several paths to different python installations. Try running an example with each of the python installations: e.g.

`/usr/bin/python3.7 -c "import bornagain"`
`/usr/bin/python3.8 -c "import bornagain"`

If this work, you will want to add the following line to your .bashrc file:
`export PYTHONPATH=$PYTHONPATH:/the/path/found/in/step1`

Let me know if this works.

**Comment by gdoerk** [comment]
Hi,

Thank you very much for your help!  Including the required directory in the PYTHONPATH environment was the key.

I installed/uninstalled python 3.8 earlier which may be part of the problem apparently.  I installed python3.7.7 using Homebrew, and also tried to run cleanup using brew, but it doesn't seem to capture directories linked with python3.8 (perhaps because it is a later version?).

Anyways, I can run BornAgain Python scripts now.   I've updated my bash_profile, and it works fine after reopening the Terminal as well.

Best regards,

Gregory Doerk
Associate Materials Scientist
Center for Functional Nanomaterials
Brookhaven National Laboratory
735 Brookhaven Avenue
Upton, NY 11973
________________________________

**Comment by juanmcloaiza** [comment]
> Thank you very much for your help!  Including the required directory in the PYTHONPATH environment was the key.

You're welcome, I'm glad it worked!

> I installed/uninstalled python 3.8 earlier which may be part of the problem apparently.  I installed python3.7.7 using Homebrew, and also tried to run cleanup using brew, but it doesn't seem to capture directories linked with python3.8 (perhaps because it is a later version?).

As a rule of thumb, if you really need to use more than one python version, you should use virtual environments, e.g. through `anaconda` or `virtualenv`. Although this advice may vary depending on your specific case.

All the best,
Juan
