### ISSUE TITLE
CTest points to broken visualization scripts

### ISSUE THREAD

**Issue by jwuttke** [scgmlz/BornAgain#946]
When a test in TestCoreStandard/FormFactors fails, then the following is printed:
```
New simulation result stored in /G/sw/ba/build/test_output/Functional/Core/FormF
actors_Dot.int.gz
To visualize an intensity map, use /G/sw/ba/build/bin/plot_intensity_data.py;   
to plot a difference image, use /G/sw/ba/build/bin/plot_intensity_data_diff.py
If the new result is correct, then move it to /G/sw/ba/Tests/ReferenceData/Core/
```
These scripts fail with messages like
```
/G/sw/ba/build/bin/plot_intensity_data.py /G/sw/ba/Tests/ReferenceData/Core/FormFactors_Dot.int.gz 
Traceback (most recent call last):
  File "/G/sw/ba/build/bin/plot_intensity_data.py", line 10, in <module>
    import bornagain as ba
  File "/usr/local/lib/BornAgain-1.16/bornagain/__init__.py", line 10, in <module>
    from libBornAgainFit import *
  File "/usr/local/lib/BornAgain-1.16/bornagain/libBornAgainFit.py", line 11, in <module>
    import _libBornAgainFit
ImportError: dynamic module does not define init function (init_libBornAgainFit)
```

**Comment by jwuttke** [comment]
Cannot reproduce, possibly resolved through PR1044 along with issue #987.
